### ISSUE TITLE
Error while getting data (line 770 - 771)

### ISSUE THREAD

**Issue by mschlenstedt** [DBa2016/sc2mqtt#3]
I got this error:

```loxberry@masterofdesaster:~/data/plugins/git/sc2mqtt $ ./sc2mqtt.py
[INFO    ]-2020-10-25 09:40:38 Getting openid config...
[INFO    ]-2020-10-25 09:40:39 Done!
[INFO    ]-2020-10-25 09:40:39 Getting authorization...
[INFO    ]-2020-10-25 09:40:39 Done!
[INFO    ]-2020-10-25 09:40:39 Parsing authorization...
[INFO    ]-2020-10-25 09:40:39 Done!
[INFO    ]-2020-10-25 09:40:39 Sending email form...
[INFO    ]-2020-10-25 09:40:39 Done!
[INFO    ]-2020-10-25 09:40:39 Parsing email form response...
[INFO    ]-2020-10-25 09:40:39 Done!
[INFO    ]-2020-10-25 09:40:39 Sending password form...
[INFO    ]-2020-10-25 09:40:40 Done!
[INFO    ]-2020-10-25 09:40:40 Done!
[INFO    ]-2020-10-25 09:40:40 Retrieving tokens...
[INFO    ]-2020-10-25 09:40:40 Done!
[INFO    ]-2020-10-25 09:40:40 Retrieving VW tokens...
[INFO    ]-2020-10-25 09:40:41 Done!
[INFO    ]-2020-10-25 09:40:41 Tokens OK
Traceback (most recent call last):
  File "./sc2mqtt.py", line 929, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.7/dist-packages/nest_asyncio.py", line 31, in run
    return loop.run_until_complete(future)
  File "/usr/local/lib/python3.7/dist-packages/nest_asyncio.py", line 95, in run_until_complete
    return f.result()
  File "/usr/lib/python3.7/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.7/asyncio/tasks.py", line 223, in __step
    result = coro.send(None)
  File "./sc2mqtt.py", line 69, in main
    await ad.init()
  File "./sc2mqtt.py", line 920, in init
    t = await self.getVehicleRights(car)
  File "./sc2mqtt.py", line 519, in getVehicleRights
    "followAllRedirects": True
  File "./sc2mqtt.py", line 771, in execRequest
    raise HTTPCodeException("Got HTTP%d; %s"%(r.status_code, r.text), r.status_code)
__main__.HTTPCodeException: ('Got HTTP401; {"error":{"errorCode":"gw.error.authentication","description":"Unauthorized"}}', 401)
```

If I comment out line 770 and 771, everything works fine and I receive correct data from the server.

**Comment by DBa2016** [comment]
The 401 return code means "unauthorized", so something went sideways during authentication. Lines 770 and 771 handle return codes over 400 (authorization issues):
```
         if r.status_code >= 400: # ignore successful and redirected codes
            raise HTTPCodeException("Got HTTP%d; %s"%(r.status_code, r.text), r.status_code)
```
Ignoring a 401 code can raise a red flag on your account, I wouldn't do it easily.

**Comment by mschlenstedt** [comment]
Account data is correct and everything is fine when I comment out the lines. I receive correct data from my cars.

**Comment by mschlenstedt** [comment]
I investigated this a little bit more. Soulution is NOT to comment out line 770-771 - you are absolutely right.

Problem with my account is, that getVehicleRights(car) seems to fail with 401. Don't know why. I haven't confirmed my account by a Skoda service partner (so I am not able to open/close the vehicle via app). Maybe this is the reason?

If I comment out grabbing the VehicleRights, everything works fine.

https://github.com/DBa2016/sc2mqtt/blob/11a6f337591ee6ab0bb3cd47306dbcfca6b80469/sc2mqtt.py#L919
